import type { Metadata } from 'next'
import { Inria_Serif, Source_Sans_3 } from 'next/font/google'
import './globals.scss'

const inria_sans = Inria_Serif({
	weight: ['400', '700'],
	subsets: ['latin'],
	variable: '--font-inria-serif',
	display: 'swap',
})

const source_sans = Source_Sans_3({
	subsets: ['latin'],
	variable: '--font-source-sans',
	display: 'swap',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html
			lang='en'
			className={`${inria_sans.variable} ${source_sans.variable}`}
		>
			<body>{children}</body>
		</html>
	)
}
